import { NextResponse } from "next/server";
import { getAgentCatalog } from "@/lib/catalog/server";
import { getRecommendations } from "@/lib/ai/tools/recommendations";
import { getUpsell } from "@/lib/ai/tools/upsell";
import { getCrossSell } from "@/lib/ai/tools/crosssell";

type Product = {
  id: string;
  name: string;
  price: number;
  inventory: number;
  category: string;
};

type Opportunity = {
  title: string;
  description: string;
  value: number;
  type: "RECOMMENDATION" | "UPSELL" | "CROSS_SELL";
};

export async function GET() {
  try {
    const catalog = await getAgentCatalog();

    const products = catalog.products as Product[];

    const availableProducts = products.filter(
      (product) =>
        product.inventory === undefined ||
        Number(product.inventory) > 0
    );

    if (availableProducts.length === 0) {
      return NextResponse.json({
        opportunities: [],
        aiRevenueOpportunity: 0,
      });
    }

    const opportunities: Opportunity[] = [];

    /*
     * AI opportunity estimation factors.
     *
     * Product prices are stored in paise.
     * Therefore all calculations below also remain in paise.
     */
    const RECOMMENDATION_RATE = 0.08;
    const CROSS_SELL_RATE = 0.10;
    const UPSELL_RATE = 0.15;

    for (const product of availableProducts.slice(0, 10)) {
      /*
       * ---------------------------------------------------------
       * RECOMMENDATIONS
       * ---------------------------------------------------------
       */
      const recommendations = await getRecommendations({
        productId: product.id,
      });

      for (const recommendation of recommendations.slice(0, 2)) {
        const recommendedProduct = recommendation.product;

        if (
          !recommendedProduct ||
          Number(recommendedProduct.inventory) <= 0
        ) {
          continue;
        }

        const estimatedRevenue = Math.round(
          Number(recommendedProduct.price) *
            RECOMMENDATION_RATE
        );

        if (estimatedRevenue <= 0) {
          continue;
        }

        opportunities.push({
          title: `${product.name} → ${recommendedProduct.name}`,
          description:
            recommendation.reason ||
            "Related product recommendation generated by SellPilot.",
          value: estimatedRevenue,
          type: "RECOMMENDATION",
        });
      }

      /*
       * ---------------------------------------------------------
       * UPSELL
       * ---------------------------------------------------------
       */
      const upsells = await getUpsell({
        productId: product.id,
      });

      for (const upsell of upsells.slice(0, 1)) {
        if (
          !upsell.product ||
          Number(upsell.product.inventory) <= 0
        ) {
          continue;
        }

        const priceDifference =
          Number(upsell.product.price) -
          Number(product.price);

        if (priceDifference <= 0) {
          continue;
        }

        const estimatedRevenue = Math.round(
          priceDifference * UPSELL_RATE
        );

        if (estimatedRevenue <= 0) {
          continue;
        }

        opportunities.push({
          title: `${product.name} → ${upsell.product.name}`,
          description:
            upsell.reason ||
            "Higher-value product opportunity identified by SellPilot.",
          value: estimatedRevenue,
          type: "UPSELL",
        });
      }

      /*
       * ---------------------------------------------------------
       * CROSS-SELL
       * ---------------------------------------------------------
       */
      const crossSells = await getCrossSell({
        productId: product.id,
      });

      for (const crossSell of crossSells.slice(0, 1)) {
        const item = crossSell.items?.[0];

        if (!item || Number(item.inventory) <= 0) {
          continue;
        }

        const estimatedRevenue = Math.round(
          Number(item.price) * CROSS_SELL_RATE
        );

        if (estimatedRevenue <= 0) {
          continue;
        }

        opportunities.push({
          title: `${product.name} + ${item.name}`,
          description:
            crossSell.reason ||
            "Complementary product opportunity identified by SellPilot.",
          value: estimatedRevenue,
          type: "CROSS_SELL",
        });
      }
    }

    /*
     * ---------------------------------------------------------
     * REMOVE DUPLICATES
     * ---------------------------------------------------------
     */
    const unique = opportunities.filter(
      (opportunity, index, array) =>
        index ===
        array.findIndex(
          (item) =>
            item.title === opportunity.title &&
            item.type === opportunity.type
        )
    );

    /*
     * Highest estimated revenue opportunities first.
     */
    unique.sort((a, b) => b.value - a.value);

    /*
     * Show the top 6 opportunities.
     */
    const finalOpportunities = unique.slice(0, 6);

    /*
     * Sum estimated additional revenue.
     *
     * IMPORTANT:
     * value is stored in paise, matching Product.price.
     */
    const aiRevenueOpportunity =
      finalOpportunities.reduce(
        (total, opportunity) =>
          total + Number(opportunity.value || 0),
        0
      );

    return NextResponse.json({
      opportunities: finalOpportunities,
      aiRevenueOpportunity,
    });
  } catch (error: unknown) {
    console.error(
      "Dashboard opportunities error:",
      error
    );

    return NextResponse.json(
      {
        opportunities: [],
        aiRevenueOpportunity: 0,
        error:
          error instanceof Error
            ? error.message
            : "Unable to calculate opportunities",
      },
      { status: 500 }
    );
  }
}