import { NextResponse } from "next/server";
import { getAgentCatalog } from "@/lib/catalog/server";
import { getRecommendations } from "@/lib/ai/tools/recommendations";
import { getUpsell } from "@/lib/ai/tools/upsell";
import { getCrossSell } from "@/lib/ai/tools/crosssell";

export async function GET() {
  try {
    const catalog = await getAgentCatalog();

    const products = catalog.products as Array<{
      id: string;
      name: string;
      price: number;
      inventory: number;
      category: string;
    }>;

    const availableProducts = products.filter(
      (product) =>
        product.inventory === undefined || product.inventory > 0
    );

    if (availableProducts.length === 0) {
      return NextResponse.json({
        opportunities: [],
        aiRevenueOpportunity: 0,
      });
    }

    const opportunities: Array<{
      title: string;
      description: string;
      value: number;
      type: string;
    }> = [];

    /*
     * Generate recommendations from the first few available products.
     * The recommendation engine itself handles category/tag matching.
     */
    for (const product of availableProducts.slice(0, 5)) {
      const recommendations = await getRecommendations({
        productId: product.id,
      });

      for (const recommendation of recommendations.slice(0, 2)) {
        const recommendedProduct = recommendation.product;

        if (!recommendedProduct || recommendedProduct.inventory <= 0) {
          continue;
        }

        opportunities.push({
          title: `${product.name} → ${recommendedProduct.name}`,
          description:
            recommendation.reason ||
            "Related product recommendation generated by SellPilot.",
          value: Math.round(recommendedProduct.price),
          type: "RECOMMENDATION",
        });
      }

      const upsells = await getUpsell({
        productId: product.id,
      });

      for (const upsell of upsells.slice(0, 1)) {
        if (!upsell.product || upsell.product.inventory <= 0) {
          continue;
        }

        opportunities.push({
          title: `${product.name} → ${upsell.product.name}`,
          description:
            upsell.reason ||
            "Higher-value product opportunity identified by SellPilot.",
          value: Math.round(
            Math.max(0, upsell.product.price - product.price)
          ),
          type: "UPSELL",
        });
      }

      const crossSells = await getCrossSell({
        productId: product.id,
      });

      for (const crossSell of crossSells.slice(0, 1)) {
        const item = crossSell.items?.[0];

        if (!item || item.inventory <= 0) {
          continue;
        }

        opportunities.push({
          title: `${product.name} + ${item.name}`,
          description:
            crossSell.reason ||
            "Complementary product opportunity identified by SellPilot.",
          value: Math.round(item.price),
          type: "CROSS_SELL",
        });
      }
    }

    /*
     * Remove duplicate opportunities.
     */
    const unique = opportunities.filter(
      (opportunity, index, array) =>
        index ===
        array.findIndex(
          (item) =>
            item.title === opportunity.title &&
            item.type === opportunity.type
        )
    );

    /*
     * Highest-value opportunities first.
     */
    unique.sort((a, b) => b.value - a.value);

    const finalOpportunities = unique.slice(0, 6);

    const aiRevenueOpportunity = finalOpportunities.reduce(
      (total, opportunity) => total + opportunity.value,
      0
    );

    return NextResponse.json({
      opportunities: finalOpportunities,
      aiRevenueOpportunity,
    });
  } catch (error: unknown) {
    console.error("Dashboard opportunities error:", error);

    return NextResponse.json(
      {
        opportunities: [],
        aiRevenueOpportunity: 0,
        error:
          error instanceof Error
            ? error.message
            : "Unable to calculate opportunities",
      },
      { status: 500 }
    );
  }
}